Repository rust-bio/rust-bio-tools, pull requests merged in 2020-11, with the labels that each got.

#79 Update vcf-report plot appearance
  src/bcf/report/gene_specs.json
  src/bcf/report/oncoprint.rs
  src/bcf/report/report_specs.json
  tests/expected/report/genes/KRAS1.html
  tests/expected/report/indexes/index1.html
Labels: enhancement

#78 Fix index out of bounce error in vcf-report
  src/bcf/report/oncoprint.rs
Labels: bug

#80 Improve table appearance for vcf-report
  src/bcf/report/css/oncoprint.css
  src/bcf/report/js/bootstrap-table.min.js
  src/bcf/report/js/table-report.js
  src/bcf/report/table_report/report_table.html.tera
  tests/expected/report/details/a/KRAS.html
  tests/expected/report/details/b/KRAS.html
  tests/lib.rs
Labels: enhancement

#82 Add parameter for additional javascript files for vcf-report
  src/bcf/report/mod.rs
  src/bcf/report/table_report/create_report_table.rs
  src/bcf/report/table_report/mod.rs
  src/bcf/report/table_report/report_table.html.tera
  src/cli.yaml
  src/main.rs
  tests/expected/report/details/a/KRAS.html
  tests/expected/report/details/b/KRAS.html
  tests/lib.rs
Labels: enhancement

#89 Fix two clippy lints
  src/bcf/annotate_dgidb.rs
  src/bcf/split.rs
Labels: enhancement

#88 Filter second stage for cannonical records
  src/bcf/report/oncoprint.rs
  tests/expected/report/genes/KRAS1.html
Labels: enhancement

#90 Add pre-commit hooks
  .pre-commit-config.yaml
  README.md
Labels: enhancement

#91 Consensus read calling: Change output to fastq
  src/bam/collapse_reads_to_fragments/calc_consensus.rs
  src/bam/collapse_reads_to_fragments/mod.rs
  src/bam/collapse_reads_to_fragments/pipeline.rs
  src/cli.yaml
  src/main.rs
  tests/expected/bam_consensus_r1.fq
  tests/expected/bam_consensus_r2.fq
  tests/expected/bam_consensus_se.fq
  tests/expected/overlapping_consensus_marked.bam
  tests/lib.rs
  tests/overlapping_consensus_marked.bam
Labels: WIP

#92 Fix problems with latest cc version
  Cargo.toml
Labels: bug
