Repository rust-bio/rust-bio-tools, pull requests merged in 2020-12, with the labels that each got.

#99 Improvements for vcf-report
  src/bcf/report/css/oncoprint.css
  src/bcf/report/gene_specs.json
  src/bcf/report/js/table-report.js
  src/bcf/report/lookup_table.html.tera
  src/bcf/report/oncoprint.rs
  src/bcf/report/prefix_table.html.tera
  src/bcf/report/report.html.tera
  src/bcf/report/report_specs.json
  src/bcf/report/table_report/create_report_table.rs
  src/bcf/report/table_report/report_table.html.tera
  src/cli.yaml
  tests/expected/report/details/a/KRAS.html
  tests/expected/report/details/b/KRAS.html
  tests/expected/report/genes/KRAS1.html
  tests/expected/report/indexes/index1.html
Labels: bug, enhancement

#100 Add threads parameter to vcf-report
  src/cli.yaml
  src/main.rs
Labels: enhancement

#101 Port clap from yml to structopt
  Cargo.toml
  src/bam/collapse_reads_to_fragments/mod.rs
  src/bam/depth.rs
  src/bcf/annotate_dgidb.rs
  src/bcf/match_variants.rs
  src/bcf/report/mod.rs
  src/bcf/report/table_report/create_report_table.rs
  src/bcf/report/table_report/mod.rs
  src/cli.rs
  src/cli.yaml
  src/fastq/collapse_reads_to_fragments/mod.rs
  src/fastq/filter.rs
  src/fastq/split.rs
  src/main.rs
Labels: enhancement

#96 Fix asynchronous consensus reads
  Cargo.toml
  src/bam/collapse_reads_to_fragments/calc_consensus.rs
  src/bam/collapse_reads_to_fragments/pipeline.rs
  src/common.rs
  tests/expected/bam_consensus_r1.fq
  tests/expected/bam_consensus_r2.fq
  tests/expected/bam_consensus_se.fq
Labels: WIP
